trigger: none

pool:
  vmImage: ubuntu-20.04

stages:
- stage: TrainDev
  displayName: Train (Dev Stage)
  jobs:
    - template: template-train-and-register.yml
      parameters:
        variablesFile: german-credit-config-dev.yml

- stage: DeployDev
  displayName: Deploy (Dev Stage)
  jobs:
    - template: template-deploy.yml
      parameters:
        variablesFile: german-credit-config-dev.yml

- stage: TrainProd
  displayName: Train (Prod Stage)
  jobs:
    - template: template-train-and-register.yml
      parameters:
        variablesFile: german-credit-config-prod.yml

- stage: DeployProd
  displayName: Deploy (Prod Stage)
  jobs:
    - template: template-deploy.yml
      parameters:
        variablesFile: german-credit-config-prod.yml