trigger:
- master
- main
- release/*
- feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Dev
  variables:
  - template: german-credit-config-dev.yml
  jobs:
  - job: Train
    displayName: Train and register model
    steps:
    - template: train-and-register.yml
