trigger:
- master
- main
- release/*
- feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Dev
  displayName: Dev Stage
  jobs:
    - template: train-and-register.yml
      parameters:
        name: Dev
        variablesFile: german-credit-config-dev.yml

- stage: Prod
  displayName: Prod Stage
  jobs:
    - template: train-and-register.yml
      parameters:
        name: Prod
        variablesFile: german-credit-config-prod.yml