trigger:
- master
- main
- release/*
- feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Dev
  displayName: Dev Stage
  jobs:
    - template: template-train-and-register.yml
      parameters:
        variablesFile: german-credit-config-dev.yml
    - template: template-deploy.yml
      parameters:
        variablesFile: german-credit-config-dev.yml
- stage: Prod
  displayName: Prod Stage
  dependsOn: Dev
  jobs:
    - template: template-train-and-register.yml
      parameters:
        variablesFile: german-credit-config-prod.yml
    - template: template-deploy.yml
      parameters:
        variablesFile: german-credit-config-dev.yml