parameters:
  variablesFile: ''

jobs:
- job: TrainAndRegister
  displayName: Train and Register Model
  variables:
  - template: ${{ parameters.variablesFile }}
  steps:
    - task: AzureCLI@2
      displayName: 'Configure AML CLI v2'
      inputs:
        azureSubscription: ${{ variables.ml_workspace_connection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az extension add -n ml -y
          az configure --defaults group=${{ variables.ml_workspace_rg }} workspace=${{ variables.ml_workspace_name }} location=${{ variables.ml_workspace_region }}


    - task: AzureCLI@2
      displayName: 'Train, explain and register model'
      inputs:
        azureSubscription: ${{ variables.ml_workspace_connection }}
        workingDirectory: ${{ variables.ml_model_path }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          job_name=`az ml job create --file azureml/train.yml | jq .name -r`
          echo "Started job with job_name: $job_name"
          az ml job stream --name $job_name
          az ml model create --name ${{ variables.ml_model_name }} --path runs:/$job_name/outputs
