parameters:
  variablesFile: ''

jobs:
- job: DeployModel
  displayName: Deploy Model
  variables:
  - template: ${{ parameters.variablesFile }}
  steps:
    - task: AzureCLI@2
      displayName: 'Configure AML CLI v2'
      inputs:
        azureSubscription: ${{ variables.ml_workspace_connection }}
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: |
          az extension add -n ml -y
          az configure --defaults group=${{ variables.ml_workspace_rg }} workspace=${{ variables.ml_workspace_name }} location=${{ variables.ml_workspace_region }}

    - task: AzureCLI@2
      displayName: 'Deploy model as Managed Online Endpoint'
      inputs:
        azureSubscription: ${{ variables.ml_workspace_connection }}
        workingDirectory: ${{ variables.ml_model_path }}
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: |
          az ml online-endpoint create --name ${{ variables.ml_endpoint_name }}
          az ml online-deployment create --endpoint-name ${{ variables.ml_endpoint_name }} \
                                         --name ${{ variables.ml_deployment_name }} \
                                         --file azureml/deployment.yml \
                                         --set model=azureml:${{ variables.ml_model_name }}@latest
