parameters:
- name: variablesFile
  default: ''

variables: 
 - template: $(variablesFile)
 
steps:
  - task: AzureCLI@2
    displayName: 'Install AML CLI'
    inputs:
      azureSubscription: $(ml-workspace-connection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az extension add -n azure-cli-ml

  - task: AzureCLI@2
    displayName: 'Attach to workspace'
    inputs:
      azureSubscription: $(ml-workspace-connection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: $(ml-model-path)
      inlineScript: |
        az ml folder attach -g $(ml-workspace-rg) -w $(ml-workspace-name)

  - task: AzureCLI@2
    displayName: 'Train and explain model'
    inputs:
      azureSubscription: $(ml-workspace-connection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: $(ml-model-path)
      inlineScript: |
        az ml run submit-script \
        --run-configuration-name config/train-amlcompute \
        --target $(ml-compute-name) \
        --experiment-name $(ml-experiment-name) \
        --output-metadata-file $(Build.ArtifactStagingDirectory)/run.json

  - task: AzureCLI@2
    displayName: 'Register model'
    inputs:
      azureSubscription: $(ml-workspace-connection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: $(ml-model-path)
      inlineScript: |
        az ml model register \
        --name $(ml-model-name) \
        --asset-path outputs/$(ml-model-filename) \
        --run-metadata-file $(Build.ArtifactStagingDirectory)/run.json \
        --output-metadata-file $(Build.ArtifactStagingDirectory)/model.json \
        --property git-repo-url=$(Build.Repository.Uri) \
        --property git-commit-id=$(Build.SourceVersion)
