variables: 
 - template: german-credit-config.yml

trigger: none

pool:
  vmImage: ubuntu-20.04

stages:
- stage: TrainModel
  displayName: Train & register model
  jobs:
  - job: TrainModel
    steps:
    - template: ../templates/configure-aml-cli.yml
    - template: ../templates/train-model.yml
    - template: ../templates/register-model.yml
    - template: ../templates/publish-artifacts.yml

- stage: DeployModel
  displayName: Deploy model
  jobs:
  - deployment: DeployModel
    displayName: Deploy Model to Managed Online Endpoint
    environment: model-production
    variables:
      ml_model_path: $(Pipeline.Workspace)/model_drop
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../templates/download-artifacts.yml
          - template: ../templates/configure-aml-cli.yml
          - template: ../templates/deploy-model.yml