variables: 
 - template: german-credit-config.yml

trigger: none

pool:
  vmImage: ubuntu-20.04

stages:
- stage: DeployTrainingPipeline
  displayName: Deploy model training pipeline
  jobs:
  - job: TrainModel
    steps:
    - template: ../templates/install-aml-sdk.yml
    - template: ../templates/configure-aml-cli.yml
    - template: ../templates/deploy-pipeline.yml