variables: 
 - template: german-credit-config.yml

trigger: none

pool:
  vmImage: ubuntu-20.04

steps:
  - task: AzureCLI@2
    displayName: 'Configure AML CLI v2'
    inputs:
      azureSubscription: $(ml_workspace_connection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az extension add -n ml -y
        az configure --defaults group=$(ml_workspace_rg) workspace=$(ml_workspace_name) location=$(ml_workspace_region)

  - task: AzureCLI@2
    displayName: 'Deploy model as Managed Online Endpoint'
    inputs:
      azureSubscription: $(ml_workspace_connection)
      workingDirectory: $(ml_model_path)
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
        # Create endpoint if it doesn't exist yet
        if [[ `az ml online-endpoint list -o tsv --query "[?name=='$(endpoint_name)'][name]" | wc -l` -ne 1 ]]; then
          az ml online-endpoint create --name $(endpoint_name) --file azureml/endpoint.yml
        else
          echo "Endpoint $(endpoint_name) already exists"
        fi
        az ml online-deployment create --file azureml/deployment.yml \
                                       --endpoint-name $(endpoint_name) \
                                       --set model=azureml:$(ml_model_name)@latest
