$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: |
  ls -R ${{inputs.training_data}}
  python train.py --data_path ${{inputs.training_data}} --model_name credit-prediction.pkl
code: ./
inputs:
  training_data:
    path: azureml:german-credit-demo-v2@latest
environment: azureml:german-credit-demo-env@latest
compute: azureml:cpu-cluster
experiment_name: german-credit-training