steps:
- task: AzureCLI@2
  displayName: 'Train and explain model'
  inputs:
    azureSubscription: $(ml_workspace_connection)
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: $(ml_model_path)
    inlineScript: |
      job_name=`az ml job create --file azureml/train.yml | jq .name -r`
      echo "Started job with job_name: $job_name"
      echo $job_name > job_name.txt
      az ml job stream --name $job_name
