steps:
- task: AzureCLI@2
  displayName: 'Train and explain model'
  inputs:
    azureSubscription: $(ml_workspace_connection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    workingDirectory: $(ml_model_path)
    inlineScript: |
      az ml run submit-script \
      --run-configuration-name config/train-amlcompute \
      --target $(ml_compute_name) \
      --experiment-name $(ml_experiment_name) \
      --output-metadata-file run.json