$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: german-credit-training
environment: azureml:german-credit-demo-env@latest
compute: azureml:cpu-cluster
command: |
  python train.py --data_path ${{inputs.training_data}}
code: ../
inputs:
  training_data:
    path: azureml:german-credit-demo@latest