$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: |
  python train.py --data_path ${{inputs.training_data}}
code: ../
inputs:
  training_data:
    path: azureml:german-credit@latest
compute: azureml:cpu-cluster
environment: azureml:german-credit-demo-env@latest
experiment_name: german-credit-basic-training